var messages = [];
var emoticonArray = {};
var userArray = {};
var user;
var lastReceivedId = 0;
var imgArray = [];
var chatInformation = {};
var language;
var currentQuote = {"content": ""};
var initialized = {"getUser":false, "getUserArray":false, "getEmoticonArray":false, "getImageArray":false, "getChatInformation":false};
var titleAlert = false;
var isActive = true;
var activeTabButton = "chat";
var customScrollbarOptionsDefault = { theme: "minimal-dark", scrollInertia: 100, scrollButtons:{ enable: true } };
var customScrollbarOptionsMessages = { theme: "dark-3", scrollInertia: 100, scrollButtons:{ enable: true } };