var messages = [];
var emoticonArray = {};
var userArray = [];
var lastReceivedId = 0;
var imgArray = [];
var chatInformation = {};
var language;
var currentQuote = {};
var initialized = {"getUserArray":false, "getEmoticonArray":false, "getImageArray":false, "getChatInformation":false};
var titleAlert = false;
var isActive= false;